- sdmetrics/__init__.py
- setup.cfg
- setup.py
Increase the numpy version upper bound to increase compatibility with other packages and relax a little bit the SDV version range to support newer versions within the current minor.
> Increase numpy version upper bound

- sdmetrics/multi_table/multi_single_table.py
- sdmetrics/single_table/bayesian_network.py
- sdmetrics/single_table/detection/base.py
- sdmetrics/single_table/detection/sklearn.py
Allow passing a SingleTable metric as an argument to MultiSingleTable metric, so MultiSingleTable metrics can be defined dynamically without the need to create a class.
Also support passing BN structure as both a tuple of tuples or as an entire dict representation of a previous BN instance.
> Dynamic MultiSingleTable metrics

- sdmetrics/__init__.py
- sdmetrics/base.py
- sdmetrics/column_pairs/__init__.py
- sdmetrics/column_pairs/base.py
- sdmetrics/column_pairs/statistical/__init__.py
- sdmetrics/column_pairs/statistical/kl_divergence.py
- sdmetrics/multi_table/__init__.py
- sdmetrics/multi_table/multi_single_table.py
- sdmetrics/single_column/__init__.py
- sdmetrics/single_column/base.py
- sdmetrics/single_table/__init__.py
- sdmetrics/single_table/efficacy/__init__.py
- sdmetrics/single_table/efficacy/binary.py
- sdmetrics/single_table/efficacy/mlefficacy.py
- sdmetrics/single_table/efficacy/multiclass.py
- sdmetrics/single_table/multi_column_pairs.py
- sdmetrics/single_table/multi_single_column.py
- tests/integration/single_table/efficacy/test_binary.py
- tests/integration/single_table/efficacy/test_multiclass.py
- tests/integration/single_table/test_single_table.py
* Add imports in all the package `__init__` files to properly expose the public API and rename a few modules and base classes to make imports shorter.
* Add a `get_subclasses`  method to the `BaseMetric` class to easily find subclasses for any type of metric
* Add a generic MLEfficacy metric which selects the type of ML problem to solve based on the target type and then applies all the metrics that exist for that type of problem.
* Add dynamic MultiSingleColumn and MultiColumnPairs metric creation like we already have for MultiSingleTable
> Organize Imports and add Generic MLEfficacy and get_subclasses

- sdmetrics/multi_table/detection/parent_child.py
- sdmetrics/multi_table/multi_single_table.py
- sdmetrics/single_table/base.py
Support passing a metadata that is not a `dict` but has a `to_dict` method. This allows passing `Metadata` and `Table` objects directly.
> Allow passing non dict metadata

- sdmetrics/single_table/efficacy/base.py
- sdmetrics/single_table/efficacy/binary.py
- sdmetrics/single_table/efficacy/mlefficacy.py
- tests/integration/single_table/efficacy/test_binary.py
- tests/integration/single_table/efficacy/test_multiclass.py
When a binary classification dataset which has a target column that is not boolean (so, instead of containing `True/False` or `0/1` it contains 2 possible categories represented by strings or numerical values other than 0 and 1), the BinaryClassification metrics fail to get a score.
This PR adds a preprocessing step that detects this situation and re-encodes the binary categorical target variable as a boolean array.
> Ensure binary classification targets are bool

- sdmetrics/single_table/gaussian_mixture.py
This PR refactors the GMLogLikelihood metric to increase its robustness by cleaning up the input data before running it through GMM and also by searching for the ideal number of components and covariance type if they are not specified in the input.
> GMLogLikelihood Robustness

- conda/meta.yaml
- sdmetrics/timeseries/ml_scorers.py
- setup.py
Updates the dependency requirements in meta.yaml to be able to use the latest versions of sktime, since only v0.5.0 and higher are available in conda-forge. It also makes a small change in the code, since sktime v0.5.0 introduces a breaking API update.
> Fixes the sktime issue for conda

- sdmetrics/single_table/__init__.py
- sdmetrics/single_table/privacy/__init__.py
Expose the `CategoricalSVM` privacy metric in the `sdmetrics.single_table` and `sdmetrics.single_table.privacy` modules.
Also use explicit imports instead of implicit.
> Expose missing metrics on the subpackage roots API

- sdmetrics/goal.py
- sdmetrics/single_table/bayesian_network.py
- sdmetrics/single_table/detection/sklearn.py
- sdmetrics/single_table/privacy/base.py
- setup.cfg
- setup.py
- tests/integration/single_column/statistical/test_cstest.py
- tests/integration/single_column/statistical/test_kstest.py
As part of #80, added `flake8-quotes` addon and adapted our code to follow this style check.
> Add `flake8-quotes`

- sdmetrics/multi_table/detection/parent_child.py
- sdmetrics/multi_table/multi_single_table.py
- sdmetrics/single_table/multi_column_pairs.py
- sdmetrics/single_table/multi_single_column.py
- sdmetrics/single_table/privacy/categorical_sklearn.py
- sdmetrics/single_table/privacy/numerical_sklearn.py
- sdmetrics/utils.py
- setup.cfg
- setup.py
As part of #80 added `pep8-naming` addon for `flake8` and adapted our code to follow this style.
> Add `pep8-naming`

- sdmetrics/column_pairs/statistical/kl_divergence.py
- sdmetrics/multi_table/detection/base.py
- sdmetrics/multi_table/multi_single_table.py
- sdmetrics/single_column/statistical/cstest.py
- sdmetrics/single_column/statistical/kstest.py
- sdmetrics/single_table/detection/base.py
- sdmetrics/single_table/efficacy/__init__.py
- sdmetrics/single_table/efficacy/binary.py
- sdmetrics/single_table/efficacy/mlefficacy.py
- sdmetrics/single_table/efficacy/multiclass.py
- sdmetrics/single_table/efficacy/regression.py
- sdmetrics/single_table/multi_column_pairs.py
- sdmetrics/single_table/multi_single_column.py
- sdmetrics/single_table/privacy/__init__.py
- sdmetrics/single_table/privacy/cap.py
- sdmetrics/single_table/privacy/categorical_sklearn.py
- sdmetrics/single_table/privacy/ensemble.py
- sdmetrics/single_table/privacy/loss.py
- sdmetrics/single_table/privacy/numerical_sklearn.py
- sdmetrics/single_table/privacy/radius_nearest_neighbor.py
- sdmetrics/single_table/privacy/util.py
- sdmetrics/timeseries/detection.py
- setup.cfg
- setup.py
As part of #80, add `flake8-docstrings` and update the code to conform with it.
**Note:** rule D107 (`__init__` docstrings) is being ignored, because in general we don't add docstrings to ``__init__``'s. This is also being ignored in RDT.
> Add `flake8-docstrings`

- setup.cfg
- setup.py
As part of #80, add `flake8-sfs` and update the code to match this addition.
**Note:** SFS3 (`String literal formatting using f-string`) is being ignored because we do so as well in RDT.
> Add `flake8-sfs`

- setup.cfg
- setup.py
- tasks.py
- tests/__init__.py
- tests/integration/__init__.py
- tests/integration/column_pairs/__init__.py
- tests/integration/column_pairs/statistical/__init__.py
- tests/integration/multi_table/__init__.py
- tests/integration/single_column/__init__.py
- tests/integration/single_column/statistical/__init__.py
- tests/integration/single_table/__init__.py
- tests/integration/timeseries/__init__.py
- tests/integration/timeseries/efficacy/__init__.py
- tests/unit/__init__.py
As part of #80, add `pydocstlyle` and update the code accordingly.
> Add `pydocstyle`

- sdmetrics/column_pairs/base.py
- sdmetrics/column_pairs/statistical/__init__.py
- sdmetrics/column_pairs/statistical/correlation_similarity.py
- sdmetrics/single_column/statistical/statistic_similarity.py
- sdmetrics/single_table/multi_column_pairs.py
- tests/unit/column_pairs/__init__.py
- tests/unit/column_pairs/statistical/__init__.py
- tests/unit/column_pairs/statistical/test_correlation_similarity.py
- tests/unit/column_pairs/test_base.py
- tests/unit/single_column/__init__.py
- tests/unit/single_column/statistical/__init__.py
- tests/unit/single_column/statistical/test_statistic_similarity.py
- tests/utils.py
> Add correlation similarity metric

- .github/workflows/integration.yml
- .github/workflows/minimum.yml
- .github/workflows/readme.yml
- .github/workflows/unit.yml
Since `macos-10.15` will soon be [deprecated](https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/), let's bump the version to `macos-latest`.
> Bump github macos version

- sdmetrics/reports/multi_table/plot_utils.py
- sdmetrics/reports/multi_table/quality_report.py
- sdmetrics/reports/single_table/plot_utils.py
- sdmetrics/reports/single_table/quality_report.py
- sdmetrics/reports/utils.py
- sdmetrics/single_table/multi_column_pairs.py
- tests/unit/reports/multi_table/test_multi_table_quality_report.py
- tests/unit/reports/single_table/test_single_table_plot_utils.py
- tests/unit/reports/single_table/test_single_table_quality_report.py
Formatting updates:
- Update `get_raw_result` output formatting
- Filter out null scores from `get_raw_result` output
- In `plot_column` util, make NaNs a category
- Make plot titles consistent & update subplot titles
- Format overall score as a percentage, and fix formatting for NaN scores
- Separate column pair tuple into two columns in `get_details`
- Update heatmap colors
Functionality fixes:
- Fix duplicate key bug for Column Pair Trends
- Fix missing value inconsistencies for real and synthetic correlation plots
- Handle edge case in single-table QualityReport where one metric has no results.
- Handle edge case in multi-table QualityReport where there is only one table (no parent-child relationship results).
- Multi table QualityReport's `show_details` and `get_details` should …
> Bug fixes for QualityReport

- sdmetrics/reports/__init__.py
- sdmetrics/reports/utils.py
- tests/unit/reports/test_utils.py
> Add plot column pair utility method

- sdmetrics/single_table/new_row_synthesis.py
Catch typeerror in new row synthesis query
Addresses this [error](https://github.com/pandas-dev/pandas/issues/22435) in older pandas versions.
> Catch typeerror in new row synthesis query

- sdmetrics/reports/multi_table/diagnostic_report.py
- sdmetrics/reports/single_table/diagnostic_report.py
- sdmetrics/reports/utils.py
- sdmetrics/single_column/statistical/category_coverage.py
- sdmetrics/single_table/new_row_synthesis.py
- tests/unit/reports/multi_table/test_multi_table_diagnostic_report.py
- tests/unit/reports/single_table/test_single_table_diagnostic_report.py
- tests/unit/single_column/statistical/test_category_coverage.py
- tests/unit/single_table/test_new_row_synthesis.py
Update Diagnostic Report
- Remove special characters from the `get_results` output
- Update print formatting and messages
- If metric is not applicable, set average metric score to `np.nan`
Update `NewRowSynthesis` metric
- Allow querying by values with new lines
- Allow querying by columns with spaces
Update `CategoryCoverage` metric
- Calculate the number of intersecting categories
> Address Diagnostic Report and metric edge cases

- sdmetrics/single_table/bayesian_network.py
- tests/integration/test_base.py
Resolves #148 
Currently, `BNLikelihood` is not returned in `SingleTableMetric.get_subclasses` because it is an intermediate child class. Move it to a terminal subclass so that it is considered a "final" implementation.
> Move BNLikelihood to a subclass

- sdmetrics/single_column/statistical/range_coverage.py
- tests/unit/single_column/statistical/test_range_coverage.py
Resolves #255 
`RangeCoverage` metric was handling input data with null values incorrectly, and returning a metric result of `NaN`.
> Fix range coverage with nan data

- sdmetrics/single_table/new_row_synthesis.py
- tests/unit/single_table/test_new_row_synthesis.py
Resolve #307 
Set the query engine to `'python'` if more than 31 `row_filter`s are specified. Trying to use the default `numexpr` will result in a `ValueError` or `Memory` error if more than 31 `row_filter`s are provided, probably due to `numpy` limiting `NPY_MAXARGS=32`.
> Fix `ValueError` in `NewRowSynthesis` if size of `row_filter` exceeds 31

- sdmetrics/multi_table/detection/parent_child.py
Resolve #328.
A note: by changing the merge from `outer` to `right`, we will be ignoring all the parent rows which do not have a corresponding child, e.g. if the child table foreign keys only cover 10% of the parent table primary keys, then 90% of the data in the parent table will be ignored. Since `_denormalize` is used to compute the similarity between real and synthetic data, the majority of the data will not be evaluated at all.
That is to say, this change will make `ParentChildDetectionMetric` evaluate **only** the matching rows, and anything else will be ignored.
> Update `ParentChildDetectionMetric _denormalize` merge type

- sdmetrics/reports/single_table/_properties/__init__.py
- sdmetrics/reports/single_table/_properties/base.py
- sdmetrics/reports/single_table/_properties/column_shapes.py
- setup.py
- tests/integration/reports/single_table/_properties/test_column_shapes.py
- tests/unit/reports/single_table/_properties/test_base.py
- tests/unit/reports/single_table/_properties/test_column_shapes.py
Resolve #355
I just have some questions:
- What should be the `progress_bar` parameter? Should it have a default value? I put `tqdm.tqdm` as default value (what is done for the reports I think)
- I didn't use the `metric` attribute for the computation, but we maybe need it at another time.
Also, I think `validate_single_table_inputs` that is in `sdmetrics.reports.utils` could be modified to better validate the `data` and `metadata`. We can define a validation method inside `BaseSingleTableProperty` maybe.
> Issue 355 column shape property

- tests/integration/reports/multi_table/_properties/test_multi_table_properties.py
Fix a rounding error that made integration crashed
> fix rounding

- sdmetrics/reports/single_table/_properties/__init__.py
- sdmetrics/reports/single_table/_properties/boundary.py
- tests/integration/reports/single_table/_properties/test_boundary.py
- tests/unit/reports/single_table/_properties/test_boundary.py
> Create single table Boundaries property

- sdmetrics/reports/single_table/_properties/__init__.py
- sdmetrics/reports/single_table/_properties/synthesis.py
- tests/integration/reports/single_table/_properties/test_synthesis.py
- tests/unit/reports/single_table/_properties/test_synthesis.py
> Create single table synthesis property

- sdmetrics/reports/base_report.py
- tests/unit/reports/test_base_report.py
> Validate that the metadata is always a dict

- sdmetrics/reports/base_report.py
- tests/integration/reports/multi_table/test_quality_report.py
- tests/integration/reports/single_table/test_quality_report.py
- tests/unit/reports/test_base_report.py
> Provide meta information about the reports

- sdmetrics/reports/multi_table/_properties/inter_table_trends.py
- tests/unit/reports/multi_table/_properties/test_inter_table_trends.py
Clickup:
CU-86ayjev9x
resolves #477 
Change the title name of graph to "Intertable Trends" instead of "Column Shapes"
> Fix title of intertable trends

- sdmetrics/reports/multi_table/_properties/inter_table_trends.py
- tests/unit/reports/multi_table/_properties/test_inter_table_trends.py
CU-86ayjeuuy
resolves #476 
Crash is caused by a string replace method on an empty dataframe. Adding an empty check and continue the `_generate_details` method for intertables.
> Don't call string replace on an empty dataframe

- sdmetrics/reports/multi_table/_properties/__init__.py
- sdmetrics/reports/multi_table/_properties/structure.py
- sdmetrics/reports/single_table/_properties/__init__.py
- sdmetrics/reports/single_table/_properties/structure.py
- tests/integration/reports/multi_table/_properties/test_structure.py
- tests/integration/reports/single_table/_properties/test_structure.py
- tests/unit/reports/multi_table/_properties/test_structure.py
- tests/unit/reports/single_table/_properties/test_structure.py
CU-86ayg9qwy
Resolve #468
Let me know if this visualization works @frances-h, @npatki
> Add `Structure` property

- sdmetrics/single_table/new_row_synthesis.py
- tests/integration/single_table/test_single_table.py
CU-860qhu3zr
Partially resolve https://github.com/sdv-dev/SDGym/issues/216 and resolve #337.
This PR adds support for datetime values as strings in `NewRowSynthesis` .
> Fix `NewRowSynthesis` on datetime columns without formats

- sdmetrics/reports/multi_table/_properties/base.py
- sdmetrics/reports/multi_table/_properties/inter_table_trends.py
- tests/integration/reports/multi_table/test_quality_report.py
- tests/unit/reports/multi_table/_properties/test_base.py
CU-86ayjkavn
#86ayjkavn
resolves #481 
Missing relationship metadata no longer throws an error but instead returns NaN for the score report for multitable data.
> Make quality reports fault tolerant on missing relationships in metadata

- sdmetrics/single_table/efficacy/base.py
> Fit on training data for `MLEfficacy`

- sdmetrics/reports/multi_table/_properties/__init__.py
- sdmetrics/reports/multi_table/_properties/data_validity.py
- sdmetrics/reports/single_table/_properties/__init__.py
- sdmetrics/reports/single_table/_properties/column_shapes.py
- sdmetrics/reports/single_table/_properties/data_validity.py
- tests/integration/reports/multi_table/_properties/test_data_validity.py
- tests/integration/reports/single_table/_properties/test_data_validity.py
- tests/unit/reports/multi_table/_properties/test_validity.py
- tests/unit/reports/single_table/_properties/test_column_shapes.py
- tests/unit/reports/single_table/_properties/test_data_validity.py
CU-86ayg9qx7
Resolve #467
The visualization is:
@frances-h, @npatki
> Add `DataValidity` property

- sdmetrics/reports/base_report.py
- sdmetrics/reports/multi_table/base_multi_table_report.py
- sdmetrics/visualization.py
- tests/unit/test_visualization.py
CU-860q76vnz
Resolves #322 
Add a function to set the `plotly` default render depending on the environment.
[Here is a notebook in google colab](https://colab.research.google.com/drive/1gKyCQX-ztpVozRxU76rHtNT1B7YFA0Tw?usp=sharing) that maintains the functionality there. Please try in a local environment to ensure that the `iframe` engine is being used.
> Fix: Sometimes graphs not being generated in jupyter notebook

- sdmetrics/errors.py
- sdmetrics/reports/single_table/_properties/structure.py
- tests/unit/reports/single_table/_properties/test_structure.py
> Single table Structure property should not have visualization

- sdmetrics/reports/multi_table/_properties/structure.py
- sdmetrics/reports/multi_table/base_multi_table_report.py
- tests/unit/reports/multi_table/_properties/test_structure.py
- tests/unit/reports/multi_table/test_base_multi_table_report.py
> Multi table Structure property visualization has incorrect styling

- sdmetrics/reports/base_report.py
- tests/unit/reports/test_base_report.py
> Report `validate` method should be private

- sdmetrics/reports/multi_table/_properties/base.py
- tests/integration/reports/multi_table/test_diagnostic_report.py
> `UserWarning: KeyError: 'relationships'` in DiagnosticReport if metadata missing relationships

- sdmetrics/reports/base_report.py
- sdmetrics/reports/multi_table/base_multi_table_report.py
- tests/unit/reports/multi_table/test_base_multi_table_report.py
- tests/unit/reports/test_base_report.py
> Running single table report on multi table data (or vice versa) results in confusing error

- sdmetrics/reports/base_report.py
- sdmetrics/reports/multi_table/base_multi_table_report.py
- sdmetrics/reports/multi_table/diagnostic_report.py
- sdmetrics/reports/single_table/diagnostic_report.py
- tests/integration/reports/single_table/test_diagnostic_report.py
- tests/unit/reports/multi_table/test_base_multi_table_report.py
- tests/unit/reports/single_table/test_diagnostic_report.py
- tests/unit/reports/test_base_report.py
CU-86ayp2dap
CU-86ayp5z2k
Resolve #508 
Resolve #509
> `ValueError` in DiagnosticReport if synthetic data does not match metadata

- sdmetrics/single_table/detection/base.py
- tests/unit/single_table/detection/test_detection.py
CU-860pbbbng
resolves #286 
Filter out columns from detection method that are not statistically modeled:
PII fields
Primary keys
Any other IDs
Text Data
> Filter out keys that cannot be statistically modeled

- sdmetrics/reports/base_report.py
- tests/unit/reports/test_base_report.py
resolve #538 
Print scores according to new spec.
> Print scores after every progress bar

- .github/workflows/dependency_checker.yml
- Makefile
- latest-requirements.txt
- latest_requirements.txt
- pyproject.toml
resolves #547 
CU-86azw20nz
Add dependency checker github action and command to see if library works with latest dependencies
> Add latest dependency checker workflow

- pyproject.toml
- tests/integration/reports/multi_table/_properties/test_column_pair_trends.py
- tests/unit/multi_table/statistical/test_cardinality_statistic_similarity.py
- tests/unit/single_column/statistical/test_statistic_similarity.py
> Add support for numpy 2.0.0

- tests/integration/test_property.py
- tests/test_property.py
> Check that every property score are index-free

- sdmetrics/reports/base_report.py
- sdmetrics/reports/multi_table/base_multi_table_report.py
- tests/unit/reports/test_base_report.py
CU-86b1d39h0
Resolve #610
Tested on SDV:
> Better error message when passing an SDV Metadata object

- sdmetrics/visualization.py
- tests/unit/test_visualization.py
> Wrong chart title when generating a box plot for just the real data using `get_column_pair_plot()` 

- pyproject.toml
- sdmetrics/column_pairs/statistical/contingency_similarity.py
- tests/integration/reports/multi_table/_properties/test_inter_table_trends.py
- tests/integration/reports/multi_table/test_quality_report.py
resolves #622 
Below is the profiling of the `QualityReport` before the changes. As you can see most time was spent in the `crosstab` method. 
To improve this, I switched to using `groupby` instead. `Groupby` seems to be faster than `crosstab` and `pivot_table` according to this [post](https://ramiro.org/notebook/pandas-crosstab-groupby-pivot/) and trials I ran. The one issue is that `groupby` returns data as a multi-indexed series instead of a table with the different column values on one axis and the different row values on the other. To compute the metric, I could either use `unstack` to convert the return value of `groupby` to the table we wanted, or change the logic to sum over the multi-indexed series. I tried both examples and show their results below. I used the same dataset for …
> Try to improve performance of contingency_similarity

- sdmetrics/single_table/table_structure.py
- tests/integration/reports/multi_table/test_diagnostic_report.py
- tests/unit/single_table/test_table_structure.py
> Add dtype comparison in `TableStructure` metric (used in Diagnostic report)

- sdmetrics/timeseries/__init__.py
- sdmetrics/timeseries/sequence_length_similarity.py
- tests/unit/timeseries/test_sequence_length_similarity.py
>  Add metric for sequence length similarity 

- sdmetrics/timeseries/__init__.py
- sdmetrics/timeseries/statistic_msas.py
- tests/unit/timeseries/test_statistic_msas.py
> Add metric for general MSAS statistics

- sdmetrics/column_pairs/statistical/contingency_similarity.py
- tests/integration/reports/multi_table/test_quality_report.py
- tests/unit/column_pairs/statistical/test_contingency_similarity.py
> When running Quality Report, ContingencySimilarity produces a RuntimeWarning (`The values in the array are unorderable.`)

- sdmetrics/column_pairs/statistical/inter_row_msas.py
- tests/unit/column_pairs/statistical/test_inter_row_msas.py
> Improve warning handling for non-positive values when `apply_log = True` for `InterRowMSAS`

- sdmetrics/column_pairs/statistical/inter_row_msas.py
- tests/unit/column_pairs/statistical/test_inter_row_msas.py
> Improve error handling for datetime values when `apply_log = True` for `InterRowMSAS`

- sdmetrics/single_column/statistical/kscomplement.py
- tests/integration/reports/multi_table/test_quality_report.py
- tests/integration/reports/single_table/_properties/test_column_shapes.py
- tests/integration/single_column/statistical/test_kscomplement.py
- tests/unit/reports/single_table/_properties/test_column_shapes.py
> Fix `KSComplement` instability for constant float values

- sdmetrics/column_pairs/statistical/inter_row_msas.py
- sdmetrics/column_pairs/statistical/statistic_msas.py
- sdmetrics/single_column/statistical/sequence_length_similarity.py
- tests/unit/column_pairs/statistical/test_inter_row_msas.py
- tests/unit/column_pairs/statistical/test_statistic_msas.py
- tests/unit/single_column/statistical/test_sequence_length_similarity.py
> Fix missing values handling for `InterRowMSAS` 

- sdmetrics/single_table/__init__.py
- sdmetrics/single_table/privacy/__init__.py
- sdmetrics/single_table/privacy/cap.py
- sdmetrics/single_table/privacy/disclosure_protection.py
- tests/integration/single_table/privacy/test_disclosure_protection.py
- tests/unit/single_table/privacy/test_cap.py
- tests/unit/single_table/privacy/test_disclosure_protection.py
> Add `DisclosureProtectionEstimate` metric

- sdmetrics/single_table/privacy/disclosure_protection.py
- tests/unit/single_table/privacy/test_disclosure_protection.py
Resolve #693, resolve #694
CU-86b34yyzp
> `DisclosureProtection` should be NaN if baseline score is zero and fix warning message

- .github/workflows/integration.yml
- .github/workflows/minimum.yml
- .github/workflows/unit.yml
- scripts/release_notes_generator.py
CU-86b3ffpek
Resolve #705 
When pushing a new commit to a PR, cancel old jobs in progress
> Cancel previous workflow runs on a new push 

- sdmetrics/single_table/data_augmentation/__init__.py
- sdmetrics/single_table/data_augmentation/base.py
- sdmetrics/single_table/data_augmentation/binary_classifier_precision_efficacy.py
- sdmetrics/single_table/data_augmentation/binary_classifier_recall_efficacy.py
- sdmetrics/single_table/data_augmentation/utils.py
- tests/integration/single_table/data_augmentation/test_binary_classifier_precision_efficacy.py
- tests/integration/single_table/data_augmentation/test_binary_classifier_recall_efficacy.py
- tests/unit/single_table/data_augmentation/test_binary_classifier_precision_efficacy.py
- tests/unit/single_table/data_augmentation/test_binary_classifier_recall_efficacy.py
- tests/unit/single_table/data_augmentation/test_utils.py
> Add `BinaryClassifierRecallEfficacy` metric

- sdmetrics/column_pairs/statistical/contingency_similarity.py
- tests/integration/column_pairs/statistical/test_contingency_similarity.py
- tests/unit/column_pairs/statistical/test_contingency_similarity.py
> Allow subsampling when computing the `ContingencySimilarity` metric

- .github/workflows/integration.yml
- .github/workflows/minimum.yml
- .github/workflows/readme.yml
- .github/workflows/unit.yml
- INSTALL.md
- pyproject.toml
- sdmetrics/single_table/bayesian_network.py
- tests/unit/single_table/test_bayesian_network.py
- tox.ini
> Support python 3.13

- sdmetrics/_utils_metadata.py
- sdmetrics/multi_table/detection/parent_child.py
- sdmetrics/multi_table/multi_single_table.py
- sdmetrics/multi_table/statistical/cardinality_shape_similarity.py
- sdmetrics/multi_table/statistical/cardinality_statistic_similarity.py
- sdmetrics/reports/base_report.py
- sdmetrics/reports/multi_table/base_multi_table_report.py
- sdmetrics/single_table/base.py
- sdmetrics/single_table/data_augmentation/base.py
- sdmetrics/single_table/data_augmentation/utils.py
- sdmetrics/timeseries/base.py
- tests/integration/single_table/data_augmentation/test_binary_classifier_precision_efficacy.py
- tests/integration/single_table/data_augmentation/test_binary_classifier_recall_efficacy.py
- tests/unit/multi_table/statistical/test_cardinality_statistic_similarity.py
- tests/unit/reports/multi_table/test_base_multi_table_report.py
- tests/unit/reports/test_base_report.py
- tests/unit/single_table/data_augmentation/test_base.py
- tests/unit/single_table/data_augmentation/test_utils.py
- tests/unit/single_table/test_bayesian_network.py
- tests/unit/test__utils_metadata.py
CU-86b3zyra8
Resolve #727
This PR contains 3 main contributions:
- Resolve #727
- Filter out PII columns for the new ML efficacy metrics (Row 3 of the bug hunt sheet but without issue filled)
- Make the `metadata validation` consistent among the entire library as we discussed @amontanez24 
Since news metrics include metadata as a parameter, it's beneficial to always refer to what's defined in _utils_metadata.py to ensure consistency.
> Use metadata to validate inputs to `BinaryClassifierEfficacy` precision and recall metrics

- .github/workflows/integration.yml
- .github/workflows/minimum.yml
- .github/workflows/unit.yml
- pyproject.toml
- sdmetrics/single_table/bayesian_network.py
- tests/unit/single_table/test_bayesian_network.py
> Upgrade `pomegranate` dependency to Python 3.13

- pyproject.toml
Failing tests on main: https://github.com/sdv-dev/SDMetrics/actions/runs/13907397105/job/38913529506?pr=747
Looks like XGBoost got a major update to [3.0.0](https://github.com/dmlc/xgboost/releases/tag/v3.0.0)
BinaryClassifier Tests are failing due to different values being calculated for our tests.
> Cap the version of XGBoost to < 3.0.0 so tests can pass

- sdmetrics/single_table/data_augmentation/binary_classifier_precision_efficacy.py
- tests/integration/single_table/data_augmentation/test_binary_classifier_precision_efficacy.py
- tests/integration/single_table/data_augmentation/test_binary_classifier_recall_efficacy.py
- tests/unit/single_table/data_augmentation/test_binary_classifier_precision_efficacy.py
- tests/unit/single_table/data_augmentation/test_binary_classifier_recall_efficacy.py
> Wrong default values for the `classifier` parameter of the `BinaryClassifierPrecisionEfficacy`

- sdmetrics/_utils_metadata.py
- sdmetrics/reports/base_report.py
- sdmetrics/reports/single_table/_properties/column_pair_trends.py
- sdmetrics/reports/utils.py
- sdmetrics/single_table/base.py
- sdmetrics/single_table/new_row_synthesis.py
- sdmetrics/timeseries/base.py
- tests/integration/single_table/data_augmentation/test_binary_classifier_recall_efficacy.py
- tests/integration/timeseries/test_timeseries.py
- tests/unit/reports/multi_table/test_base_multi_table_report.py
- tests/unit/reports/test_base_report.py
- tests/unit/reports/test_utils.py
- tests/unit/test__utils_metadata.py
- tests/unit/timeseries/test_timeseries.py
> Consolidate handling of datetime columns

- sdmetrics/visualization.py
- tests/unit/test_visualization.py
resolves #757 
CU-86b4e3whq
Handle when there is nan values only for both `distplot` and `bar` types.
Updated Font size
> Produce empty plot if all values are null for `get_column_plot`

- sdmetrics/single_table/__init__.py
- sdmetrics/single_table/privacy/__init__.py
- sdmetrics/single_table/privacy/dcr_baseline_protection.py
- sdmetrics/single_table/privacy/dcr_overfitting_protection.py
- sdmetrics/single_table/privacy/dcr_utils.py
- sdmetrics/single_table/privacy/util.py
- tests/integration/single_table/privacy/test_dcr_baseline_protection.py
- tests/integration/single_table/privacy/test_dcr_overfitting_protection.py
- tests/integration/single_table/privacy/test_dcr_utils.py
- tests/unit/single_table/privacy/test_dcr_baseline_protection.py
- tests/unit/single_table/privacy/test_dcr_overfitting_protection.py
- tests/unit/single_table/privacy/test_dcr_utils.py
- tests/unit/single_table/privacy/test_util.py
- tests/utils.py
This is the feature branch for #719 and #720.
resolves #719 
resolves #720 
resolves #739 
CU-86b3w869f
CU-86b3w7pbq
This branch consists of only approved PRs:
#726 
#728 
#733 
#745 
#752 
#746 
#751 
#754 
#756 
#760
> Add DCRBaselineProtection and DCROverfittingProtection metrics

- HISTORY.md
- static_code_analysis.txt
> v0.20.1 Release Preparation

- sdmetrics/visualization.py
- tests/unit/test_visualization.py
CU-86b4g8r3b
Resolve #759
Here are the visuals; let me know if they work. (For Figs 1 and 3, I placed my mouse over the violin to see what is shown.) @npatki
> Add a violin plot visualizations to compare a pair of columns

- HISTORY.md
- static_code_analysis.txt
> v0.21.0 Release Preparation

- .github/workflows/dependency_checker.yml
- .github/workflows/lint.yml
- .github/workflows/prepare_release.yml
> Update python setup step in workflows to use latest python version

- sdmetrics/single_table/__init__.py
- sdmetrics/single_table/data_augmentation/base.py
- sdmetrics/single_table/data_augmentation/utils.py
- sdmetrics/single_table/equalized_odds.py
- sdmetrics/single_table/privacy/dcr_overfitting_protection.py
- sdmetrics/single_table/privacy/dcr_utils.py
- sdmetrics/single_table/privacy/util.py
- sdmetrics/single_table/utils.py
- tests/integration/reports/single_table/_properties/test_column_pair_trends.py
- tests/integration/reports/single_table/test_quality_report.py
- tests/integration/single_table/test_equalized_odds.py
- tests/unit/single_table/data_augmentation/test_utils.py
- tests/unit/single_table/privacy/test_dcr_overfitting_protection.py
- tests/unit/single_table/privacy/test_dcr_utils.py
- tests/unit/single_table/test_equalized_odds.py
> Add `EqualizedOddsImprovement` metric

- sdmetrics/reports/base_report.py
- sdmetrics/reports/multi_table/_properties/base.py
- sdmetrics/reports/single_table/_properties/base.py
- sdmetrics/reports/single_table/_properties/column_pair_trends.py
- sdmetrics/reports/utils.py
- sdmetrics/single_table/privacy/util.py
- tests/integration/reports/single_table/test_quality_report.py
- tests/unit/reports/multi_table/test_base_multi_table_report.py
- tests/unit/reports/test_base_report.py
> Allow me to turn off or control any subsampling done within the quality report
