- sdmetrics/__init__.py
- sdmetrics/detection/tabular/base.py
- sdmetrics/statistical/univariate/cstest.py
- setup.cfg
- setup.py
* Also remove the child key from the tables before running parent_child_detection metrics
* Handle an edge-case in cstest when there is only one category
> Minor bugfixes

- conda/README.md
> Fixes readme typo

- README.md
- sdmetrics/timeseries/README.md
- sdmetrics/timeseries/__init__.py
- sdmetrics/timeseries/base.py
- sdmetrics/timeseries/detection.py
- setup.py
- tests/integration/timeseries/test_timeseries.py
Add Time Series Detection metrics
> Timeseries metrics

- sdmetrics/timeseries/README.md
- sdmetrics/timeseries/__init__.py
- sdmetrics/timeseries/detection.py
- sdmetrics/timeseries/efficacy/__init__.py
- sdmetrics/timeseries/efficacy/base.py
- sdmetrics/timeseries/efficacy/classification.py
- sdmetrics/timeseries/ml_scorers.py
- tests/integration/timeseries/efficacy/test_classification.py
- tests/integration/timeseries/test_timeseries.py
Add Time Series Classification Metrics.
Also refactor the Time Series Detection metrics to re-use shared parts.
> Timeseries efficacy metrics

- sdmetrics/multi_table/detection/parent_child.py
> Fix KeyError bug in ParentChildDetection metrics

- sdmetrics/timeseries/ml_scorers.py
> Changed enforce_sorted to False

- sdmetrics/single_table/detection/base.py
> Fixes more splits than classes issue

- README.md
- conda/README.md
- conda/meta.yaml
Updates readme and meta.yaml to include torch, as well as updates rdt's version requirements.
> Update conda dependencies

- .github/workflows/tests.yml
- conda/meta.yaml
- setup.py
- tasks.py
- tox.ini
Curate dependencies to match the rest of the sdv-dev libraries
Also add minimum version testing on github actions
> Curate dependencies

- conda/meta.yaml
- sdmetrics/single_table/__init__.py
- setup.py
- tasks.py
- tests/integration/single_table/efficacy/test_binary.py
- tests/integration/single_table/efficacy/test_multiclass.py
- tests/integration/single_table/efficacy/test_regression.py
- tests/integration/single_table/test_gaussian_mixture.py
- tests/integration/single_table/test_single_table.py
It also bumps the rdt dependency requirements to 0.4.1.
> Adds privacy metrics to the exports

- sdmetrics/single_table/bayesian_network.py
- setup.py
- tasks.py
> Makes pomegranate optional

- setup.cfg
- setup.py
As part of #80, add all `flake8` addons which do not require any code changes.
> Add `flake8` addons that pass in the existing code

- setup.py
- tests/integration/multi_table/test_multi_single_table.py
- tests/integration/single_table/efficacy/test_binary.py
- tests/integration/single_table/efficacy/test_multiclass.py
- tests/integration/single_table/efficacy/test_regression.py
- tests/integration/single_table/test_gaussian_mixture.py
- tests/integration/single_table/test_single_table.py
- tests/unit/test_base.py
As part of #80, adds `flake8-pytest-style` and adapt the current code to pass this lint.
> Add `flake8-pytest-style `

- sdmetrics/demos.py
- setup.cfg
- setup.py
As part of #80 , added `dlint` and adapted the code.
> Add `dlint`

- sdmetrics/__init__.py
- sdmetrics/errors.py
- sdmetrics/single_table/base.py
- sdmetrics/single_table/detection/base.py
- sdmetrics/single_table/gaussian_mixture.py
- sdmetrics/single_table/privacy/base.py
- sdmetrics/single_table/privacy/ensemble.py
Resolves #107 
Resolves [647](https://github.com/sdv-dev/SDV/issues/647)
> Capture metric errors in compute_metrics

- sdmetrics/multi_table/multi_single_table.py
Multi table metrics should only error if all single table metrics have errored.
Resolves #109
> Fix multi table metric error handling

- setup.py
> Cap pomegranate to <14.7. Issue #116

- README.md
- sdmetrics/multi_table/README.md
- sdmetrics/multi_table/__init__.py
- sdmetrics/multi_table/multi_single_table.py
- sdmetrics/single_column/README.md
- sdmetrics/single_column/__init__.py
- sdmetrics/single_column/statistical/__init__.py
- sdmetrics/single_column/statistical/kscomplement.py
- sdmetrics/single_table/README.md
- sdmetrics/single_table/__init__.py
- sdmetrics/single_table/multi_single_column.py
- sdmetrics/utils.py
- tests/integration/multi_table/test_multi_single_table.py
- tests/integration/single_column/statistical/test_kscomplement.py
- tests/integration/single_table/test_single_table.py
> New features for `KSTest.compute`

- README.md
Update the current slack invite link to a new one since the old one expired.
> Update slack invite link.

- sdmetrics/single_column/statistical/__init__.py
- sdmetrics/single_column/statistical/statistic_similarity.py
- tests/unit/single_column/statistical/test_statistic_similarity.py
> Add statistic similarity metric

- sdmetrics/multi_table/multi_single_table.py
- sdmetrics/single_table/multi_single_column.py
- tests/unit/multi_table/test_multi_single_table.py
- tests/unit/single_table/test_multi_single_column.py
> Compute score breakdown for `multi_single_column`

- sdmetrics/single_column/statistical/__init__.py
- sdmetrics/single_column/statistical/category_coverage.py
- tests/unit/single_column/statistical/test_category_coverage.py
> Add category coverage metric

- sdmetrics/column_pairs/statistical/__init__.py
- sdmetrics/column_pairs/statistical/contingency_similarity.py
- sdmetrics/single_table/multi_column_pairs.py
- test_contingency_similarity.py
- tests/unit/column_pairs/statistical/test_contingency_similarity.py
> Add contingency similarity metric

- sdmetrics/multi_table/__init__.py
- sdmetrics/multi_table/statistical/__init__.py
- sdmetrics/multi_table/statistical/cardinality_shape_similarity.py
- tests/unit/multi_table/statistical/test_cardinality_shape_similarity.py
> Add cardinality shape similarity metric

- .github/ISSUE_TEMPLATE/feature_request.md
Use "feature request" instead of "new feature"
> Update the default tags for a feature request

- sdmetrics/multi_table/__init__.py
- sdmetrics/multi_table/multi_single_table.py
- sdmetrics/single_column/statistical/category_coverage.py
- sdmetrics/single_column/statistical/missing_value_similarity.py
- sdmetrics/single_table/__init__.py
- sdmetrics/single_table/multi_single_column.py
Add new metrics to the single- and multi-table levels.
> Add wrapper classes for new single and multi table metrics

- conda/meta.yaml
- sdmetrics/timeseries/README.md
- sdmetrics/timeseries/__init__.py
- sdmetrics/timeseries/detection.py
- sdmetrics/timeseries/efficacy/__init__.py
- sdmetrics/timeseries/efficacy/classification.py
- sdmetrics/timeseries/ml_scorers.py
- setup.py
- tests/integration/timeseries/efficacy/test_classification.py
- tests/integration/timeseries/test_timeseries.py
Resolve #171 
This also allows us to remove our dependency on `pyts`.
> Remove `TSFClassifierEfficacy` and `TSFCDetection`

- README.md
- sdmetrics/multi_table/README.md
- sdmetrics/multi_table/__init__.py
- sdmetrics/multi_table/multi_single_table.py
- sdmetrics/single_table/README.md
- sdmetrics/single_table/__init__.py
- sdmetrics/single_table/multi_single_column.py
- tests/integration/single_table/test_single_table.py
> Remove KSTestExtended

- sdmetrics/timeseries/detection.py
- sdmetrics/timeseries/efficacy/base.py
> Remove `rdt` hypertransformer from timeseries metrics

- sdmetrics/single_table/efficacy/base.py
- sdmetrics/timeseries/detection.py
- sdmetrics/timeseries/efficacy/base.py
- sdmetrics/timeseries/ml_scorers.py
Resolves #178 
Also replace another rdt HyperTransformer usage with the utility HyperTransformer
> Replace LabelEncodingTransformer

- sdmetrics/single_table/detection/base.py
- sdmetrics/single_table/efficacy/base.py
- sdmetrics/timeseries/detection.py
- sdmetrics/timeseries/efficacy/base.py
- sdmetrics/timeseries/ml_scorers.py
- sdmetrics/utils.py
- tests/unit/test_utils.py
> Update detection metrics to remove rdt

- conda/meta.yaml
- setup.py
> Remove rdt as a dependency

- sdmetrics/column_pairs/statistical/contingency_similarity.py
- sdmetrics/column_pairs/statistical/correlation_similarity.py
- sdmetrics/multi_table/statistical/cardinality_statistic_similarity.py
- sdmetrics/single_column/statistical/boundary_adherence.py
- sdmetrics/single_column/statistical/category_coverage.py
- sdmetrics/single_column/statistical/missing_value_similarity.py
- sdmetrics/single_column/statistical/statistic_similarity.py
- sdmetrics/single_column/statistical/tv_complement.py
- sdmetrics/warnings.py
- tests/integration/multi_table/test_statistical_metrics.py
- tests/integration/single_table/test_single_table.py
- tests/unit/column_pairs/statistical/test_correlation_similarity.py
- tests/unit/multi_table/statistical/test_cardinality_statistic_similarity.py
- tests/unit/single_column/statistical/test_statistic_similarity.py
Add integration tests for the new metrics, and add some fixes for edge cases and class methods.
> Add integration tests and fixes

- sdmetrics/column_pairs/__init__.py
- sdmetrics/column_pairs/statistical/correlation_similarity.py
- sdmetrics/single_column/__init__.py
Update null value handling in `CorrelationSimilarity` metric.
Also update imports.
> Handle null values correctly

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
> Auto apply 'new' label for new issues

- sdmetrics/reports/__init__.py
- sdmetrics/reports/single_table/__init__.py
- sdmetrics/reports/single_table/quality_report.py
- setup.py
- tests/unit/reports/single_table/test_quality_report.py
> Add single table quality report

- sdmetrics/reports/single_table/quality_report.py
- tests/unit/reports/single_table/test_quality_report.py
> Add `QualityReport` save and load

- sdmetrics/column_pairs/statistical/correlation_similarity.py
- sdmetrics/reports/single_table/plot_utils.py
- sdmetrics/reports/single_table/quality_report.py
- sdmetrics/single_table/multi_column_pairs.py
- setup.py
- tests/unit/reports/single_table/test_plot_utils.py
- tests/unit/reports/single_table/test_quality_report.py
> Add single table visualizations

- sdmetrics/reports/single_table/quality_report.py
- tests/unit/reports/single_table/test_quality_report.py
> Update single table quality report api

- sdmetrics/reports/__init__.py
- sdmetrics/reports/utils.py
- tests/unit/reports/test_utils.py
> Add plot column utility method

- sdmetrics/reports/multi_table/quality_report.py
- sdmetrics/reports/single_table/quality_report.py
- tests/unit/reports/multi_table/test_multi_table_quality_report.py
- tests/unit/reports/single_table/test_single_table_quality_report.py
> Add multi table get details method

- sdmetrics/column_pairs/statistical/contingency_similarity.py
- sdmetrics/reports/multi_table/quality_report.py
- sdmetrics/reports/single_table/plot_utils.py
- sdmetrics/reports/single_table/quality_report.py
- sdmetrics/reports/utils.py
- sdmetrics/single_table/multi_single_column.py
- tests/unit/reports/multi_table/test_multi_table_quality_report.py
- tests/unit/reports/single_table/test_single_table_plot_utils.py
- tests/unit/reports/single_table/test_single_table_quality_report.py
- tests/unit/reports/test_utils.py
Discretize numerical and datetime columns so that we can calculate correlations between numerical & datetime columns with categorical columns.
> Update column pair metric calculation

- sdmetrics/reports/__init__.py
- sdmetrics/reports/multi_table/quality_report.py
- sdmetrics/reports/single_table/quality_report.py
- sdmetrics/reports/utils.py
- sdmetrics/single_table/multi_single_column.py
- tests/unit/reports/multi_table/test_multi_table_quality_report.py
- tests/unit/reports/single_table/test_single_table_quality_report.py
- tests/unit/reports/test_utils.py
Update the visualization method names.
Also handle `IncomputableMetricError` and a empty slices warning.
> Visualization API update

- sdmetrics/reports/multi_table/quality_report.py
- sdmetrics/reports/single_table/quality_report.py
- sdmetrics/reports/utils.py
- tests/unit/reports/multi_table/test_multi_table_quality_report.py
- tests/unit/reports/single_table/test_single_table_quality_report.py
- tests/unit/reports/test_utils.py
Update single- and multi-table QualityReports to handle and display metric errors when necessary
> Update error handling for reports

- sdmetrics/reports/single_table/plot_utils.py
- sdmetrics/single_table/base.py
- sdmetrics/single_table/bayesian_network.py
- sdmetrics/single_table/detection/base.py
- sdmetrics/single_table/efficacy/base.py
- sdmetrics/single_table/gaussian_mixture.py
- sdmetrics/single_table/multi_column_pairs.py
- sdmetrics/single_table/multi_single_column.py
- sdmetrics/single_table/privacy/base.py
- tests/integration/reports/__init__.py
- tests/integration/reports/multi_table/__init__.py
- tests/integration/reports/multi_table/test_multi_table_quality_report.py
- tests/integration/reports/single_table/__init__.py
- tests/integration/reports/single_table/test_single_table_quality_report.py
- tests/unit/single_table/test_base.py
- tests/unit/single_table/test_multi_single_column.py
Parse date data as pandas datetime in all single-table metrics.
> Parse date as datetime

- sdmetrics/multi_table/__init__.py
- sdmetrics/multi_table/multi_single_table.py
- sdmetrics/reports/single_table/plot_utils.py
- sdmetrics/single_column/__init__.py
- sdmetrics/single_column/statistical/__init__.py
- sdmetrics/single_column/statistical/range_coverage.py
- sdmetrics/single_table/__init__.py
- sdmetrics/single_table/multi_single_column.py
- tests/unit/single_column/statistical/test_range_coverage.py
> Add range coverage metric

- sdmetrics/single_table/detection/sklearn.py
- sdmetrics/single_table/efficacy/base.py
- sdmetrics/single_table/efficacy/binary.py
- sdmetrics/single_table/efficacy/mlefficacy.py
- sdmetrics/single_table/efficacy/multiclass.py
- sdmetrics/single_table/efficacy/regression.py
- tests/integration/single_table/efficacy/test_binary.py
- tests/integration/single_table/efficacy/test_multiclass.py
- tests/integration/single_table/efficacy/test_regression.py
Update API for efficacy metrics
- Change `real_data`, `real_target`, etc -> `test_data`, `test_target`, etc
- Change `synthetic_` -> `train_`
> Update efficacy metrics API

- sdmetrics/reports/multi_table/quality_report.py
- sdmetrics/reports/single_table/quality_report.py
- tests/unit/reports/multi_table/test_multi_table_quality_report.py
- tests/unit/reports/single_table/test_single_table_quality_report.py
Save sdmetrics version being used and validate upon load
> Save version

- sdmetrics/reports/single_table/plot_utils.py
- tests/unit/reports/single_table/test_single_table_plot_utils.py
Skip nan scores in column pairs visualization
> Fix column pairs visualization bug

- sdmetrics/errors.py
- sdmetrics/reports/utils.py
- tests/unit/reports/test_utils.py
Update plot utilities API and validate new inputs
New APIs:
```
utils.get_column_plot(
real_data=real_table,
synthetic_data=synthetic_table,
column_name='age',
metadata=my_metadata_dict
)
```
```
utils.get_column_pair_plot(
real_data,
synthetic_data,
column_names=['age', 'gender'],
metadata=metadata
)
```
> Update plot utilities API

- README.md
- conda/README.md
- conda/meta.yaml
- sdmetrics/timeseries/ml_scorers.py
- setup.py
- tasks.py
Remove sdmetric's torch dependency
Import it in the metric that uses it, and throw an error if not installed.
> Remove torch dependency

- sdmetrics/multi_table/multi_single_table.py
- sdmetrics/reports/single_table/__init__.py
- sdmetrics/reports/single_table/diagnostic_report.py
- sdmetrics/single_table/base.py
- tests/unit/reports/single_table/test_single_table_diagnostic_report.py
Resolves #209
Resolves #210 
Resolves #212
> Add single table diagnostic report

- sdmetrics/reports/single_table/diagnostic_report.py
- sdmetrics/reports/single_table/plot_utils.py
- sdmetrics/single_table/new_row_synthesis.py
- tests/unit/reports/single_table/test_single_table_diagnostic_report.py
- tests/unit/reports/single_table/test_single_table_plot_utils.py
> Add single table diagnostic report visualizations

- README.md
- sdmetrics/reports/multi_table/diagnostic_report.py
- sdmetrics/reports/multi_table/quality_report.py
- sdmetrics/reports/single_table/diagnostic_report.py
- sdmetrics/reports/single_table/quality_report.py
- tests/integration/reports/multi_table/test_multi_table_quality_report.py
- tests/integration/reports/single_table/test_single_table_quality_report.py
- tests/unit/reports/multi_table/test_multi_table_quality_report.py
- tests/unit/reports/single_table/test_single_table_quality_report.py
Resolves #254 
Also make the same changes for `Diagnostic Report`
> Fix quality report inconsistency

- sdmetrics/reports/utils.py
> Change columns to column_names

- sdmetrics/single_table/new_row_synthesis.py
- tests/unit/single_table/test_new_row_synthesis.py
> Use base class method to get valid fields for type

- README.md
> Fix README BoundaryAdherence Example

- sdmetrics/single_column/statistical/tv_complement.py
- tests/unit/single_column/statistical/test_tv_complement.py
> Update TVComplement to handle all nans

- sdmetrics/reports/single_table/plot_utils.py
- tests/unit/reports/single_table/test_single_table_plot_utils.py
> Handle error in visualization utility method

- sdmetrics/reports/utils.py
- sdmetrics/single_table/base.py
- sdmetrics/utils.py
- tests/unit/reports/test_utils.py
- tests/unit/single_table/test_base.py
- tests/unit/test_utils.py
> Filter out additional sdtypes

- sdmetrics/reports/utils.py
- tests/unit/reports/test_utils.py
> Support new metadata for `datetime_format`

- sdmetrics/reports/utils.py
- tests/unit/reports/test_utils.py
> Fix string datetime columns not appearing in `get_column_pair_plot`

- sdmetrics/reports/utils.py
- tests/unit/reports/test_utils.py
> Fix `ValueError` in `get_column_plot` if column is datetime string

- sdmetrics/reports/multi_table/diagnostic_report.py
- sdmetrics/reports/multi_table/quality_report.py
- sdmetrics/reports/single_table/diagnostic_report.py
- sdmetrics/reports/single_table/quality_report.py
- sdmetrics/reports/utils.py
- sdmetrics/utils.py
- tests/unit/reports/multi_table/test_multi_table_diagnostic_report.py
- tests/unit/reports/multi_table/test_multi_table_quality_report.py
- tests/unit/reports/test_utils.py
> Better extra categoricals warning message

- sdmetrics/multi_table/multi_single_table.py
- sdmetrics/reports/multi_table/diagnostic_report.py
- tests/unit/multi_table/test_multi_single_table.py
- tests/unit/reports/multi_table/test_multi_table_diagnostic_report.py
> Fix `NewRowSynthesis` having wrong `synthetic_sample_size` for Multi Table `DiagnosticReport`

- sdmetrics/column_pairs/statistical/correlation_similarity.py
- sdmetrics/multi_table/multi_single_table.py
- sdmetrics/warnings.py
> More detailed warning in `QualityReport` for constant input

- sdmetrics/reports/utils.py
- sdmetrics/timeseries/detection.py
- sdmetrics/timeseries/efficacy/base.py
- sdmetrics/timeseries/ml_scorers.py
- setup.py
- tasks.py
> Remove upper bound for `pandas`

- sdmetrics/reports/multi_table/diagnostic_report.py
- sdmetrics/reports/single_table/diagnostic_report.py
- tests/unit/reports/multi_table/test_multi_table_diagnostic_report.py
- tests/unit/reports/single_table/test_single_table_diagnostic_report.py
> Make DiagnosticReport more fault tolerant

- sdmetrics/single_table/new_row_synthesis.py
- sdmetrics/utils.py
- tests/integration/single_table/test_single_table.py
> Issue 327 newrowsynthesis special characters in column name.

- setup.py
> Uncap torch

- sdmetrics/reports/single_table/_properties/__init__.py
- sdmetrics/reports/single_table/_properties/base.py
- tests/unit/reports/single_table/_properties/__init__.py
- tests/unit/reports/single_table/_properties/test_base.py
> Create single table BaseProperty class

- sdmetrics/reports/multi_table/_properties/__init__.py
- sdmetrics/reports/multi_table/_properties/base.py
- tests/unit/reports/multi_table/_properties/__init__.py
- tests/unit/reports/multi_table/_properties/test_base.py
> Add `BaseMultiTable` property

- sdmetrics/reports/multi_table/quality_report.py
- tests/integration/reports/multi_table/test_multi_table_quality_report.py
- tests/unit/reports/multi_table/test_multi_table_quality_report.py
> Rename `'Parent Child Relationships'` property to `'Cardinality'`

- sdmetrics/reports/multi_table/_properties/__init__.py
- sdmetrics/reports/multi_table/_properties/base.py
- sdmetrics/reports/multi_table/_properties/column_pair_trends.py
- sdmetrics/reports/multi_table/_properties/column_shapes.py
- tests/integration/reports/multi_table/_properties/test_multi_table_properties.py
- tests/unit/reports/multi_table/_properties/test_base.py
- tests/unit/reports/multi_table/_properties/test_column_pair_trends.py
- tests/unit/reports/multi_table/_properties/test_column_shapes.py
> Create multi table column shapes and column pair trends properties

- sdmetrics/reports/single_table/quality_report.py
- tests/integration/reports/single_table/test_single_table_quality_report.py
- tests/unit/reports/single_table/test_single_table_quality_report.py
> More accurate progress bar for single table Quality Report

- sdmetrics/reports/multi_table/quality_report.py
- tests/unit/reports/multi_table/test_multi_table_quality_report.py
> More accurate progress bar for multi table Quality Report

- sdmetrics/reports/multi_table/_properties/base.py
- sdmetrics/reports/single_table/_properties/base.py
- sdmetrics/reports/single_table/_properties/column_pair_trends.py
- sdmetrics/reports/single_table/_properties/column_shapes.py
- sdmetrics/reports/single_table/quality_report.py
- tests/integration/reports/multi_table/_properties/test_multi_table_properties.py
- tests/integration/reports/multi_table/test_multi_table_quality_report.py
- tests/integration/reports/single_table/_properties/test_column_pair_trends.py
- tests/integration/reports/single_table/_properties/test_column_shapes.py
- tests/integration/reports/single_table/test_single_table_quality_report.py
Resolve #401
Added a fix for the multi-table to handle `NaN` in the property score.
> Don't modify the rounding in the quality report

- sdmetrics/reports/multi_table/_properties/cardinality.py
- tests/integration/reports/multi_table/_properties/test_cardinality.py
> Cardinality property misses relationships

- sdmetrics/reports/multi_table/plot_utils.py
- sdmetrics/reports/multi_table/quality_report.py
- sdmetrics/reports/single_table/plot_utils.py
- tests/integration/reports/multi_table/test_multi_table_quality_report.py
- tests/unit/reports/multi_table/test_multi_table_plot_utils.py
- tests/unit/reports/multi_table/test_multi_table_quality_report.py
> Update QualityReport properties return value

- sdmetrics/reports/multi_table/_properties/base.py
- tests/integration/reports/multi_table/_properties/test_multi_table_properties.py
- tests/integration/reports/multi_table/test_multi_table_quality_report.py
- tests/unit/reports/multi_table/_properties/test_base.py
> Overall property score should be the average across all breakdowns

- sdmetrics/reports/single_table/quality_report.py
> Fix Single Table Quality Report rounding

- sdmetrics/reports/multi_table/plot_utils.py
- sdmetrics/reports/single_table/_properties/column_pair_trends.py
- sdmetrics/reports/single_table/_properties/column_shapes.py
- sdmetrics/reports/single_table/plot_utils.py
- sdmetrics/reports/utils.py
- tests/unit/reports/single_table/_properties/test_column_shapes.py
- tests/unit/reports/test_utils.py
> Increase font size for visualizations

- sdmetrics/errors.py
- sdmetrics/reports/single_table/_properties/boundary.py
- tests/integration/reports/single_table/_properties/test_boundary.py
- tests/unit/reports/single_table/_properties/test_boundary.py
> Add skip `NaN` columns for `BoundaryAdherence` property

- sdmetrics/reports/multi_table/base_multi_table_report.py
- tests/integration/reports/multi_table/test_diagnostic_report.py
- tests/integration/reports/multi_table/test_quality_report.py
- tests/unit/reports/multi_table/test_base_multi_table_report.py
> Always show `Table` column in `get_details`

- sdmetrics/reports/multi_table/_properties/base.py
- sdmetrics/reports/single_table/_properties/boundary.py
- sdmetrics/reports/single_table/_properties/column_pair_trends.py
- sdmetrics/reports/single_table/_properties/synthesis.py
- tests/integration/reports/single_table/test_diagnostic_report.py
- tests/unit/reports/multi_table/test_base_multi_table_report.py
> Fix np.nan being shown in the results

- sdmetrics/single_column/statistical/tv_complement.py
- tests/unit/single_column/statistical/test_tv_complement.py
> Make `TVComplement` error out when no data is passed

- sdmetrics/reports/base_report.py
- tests/integration/reports/multi_table/test_diagnostic_report.py
- tests/integration/reports/multi_table/test_quality_report.py
- tests/integration/reports/single_table/test_diagnostic_report.py
- tests/integration/reports/single_table/test_quality_report.py
- tests/unit/reports/test_base_report.py
Resolve #431 
- Add missing line that was deleted from #436 
- Add tests to test object datetimes in reports
> Fix convert datetimes in BaseReport

- sdmetrics/reports/single_table/_properties/column_pair_trends.py
> Quality report is printing out a long warning message

- CONTRIBUTING.rst
- INSTALL.md
- Makefile
- README.md
- RELEASE.md
> Switch default branch from master to main

- sdmetrics/reports/multi_table/_properties/__init__.py
- sdmetrics/reports/multi_table/_properties/base.py
- sdmetrics/reports/multi_table/_properties/cardinality.py
- sdmetrics/reports/multi_table/_properties/inter_table_trends.py
- sdmetrics/reports/multi_table/base_multi_table_report.py
- sdmetrics/reports/multi_table/quality_report.py
- sdmetrics/reports/single_table/_properties/column_pair_trends.py
- setup.cfg
- tests/integration/reports/multi_table/_properties/test_inter_table_trends.py
- tests/integration/reports/multi_table/test_quality_report.py
- tests/unit/reports/multi_table/_properties/test_base.py
- tests/unit/reports/multi_table/_properties/test_inter_table_trends.py
- tests/unit/reports/multi_table/test_quality_report.py
- tests/utils.py
> Add `InterTableTrends` property

- sdmetrics/single_column/statistical/boundary_adherence.py
- tests/unit/single_column/statistical/test_boundary_adherence.py
> Fix `BoundaryAdherence` NaN handling

- sdmetrics/single_column/__init__.py
- sdmetrics/single_column/statistical/__init__.py
- sdmetrics/single_column/statistical/category_adherence.py
- tests/unit/single_column/statistical/test_category_adherence.py
Clickup task: CU-86ayfd4mw
Resolve #462
> Add `CategoryAdherence` metric

- sdmetrics/single_column/__init__.py
- sdmetrics/single_column/statistical/__init__.py
- sdmetrics/single_column/statistical/key_uniqueness.py
- tests/unit/single_column/statistical/test_key_uniqueness.py
Clickup task: CU-86ayfczkn
Resolve #460
> Add `KeyUniqueness` metric

- sdmetrics/column_pairs/__init__.py
- sdmetrics/column_pairs/statistical/__init__.py
- sdmetrics/column_pairs/statistical/cardinality_boundary_adherence.py
- tests/unit/column_pairs/statistical/test_cardinality_boundary_adherence.py
> Add CardinalityBoundaryAdherence metric

- sdmetrics/reports/multi_table/_properties/inter_table_trends.py
>  Multiple `FutureWarning` lines printed out when running the Quality Report (Intertable Trends property)

- sdmetrics/reports/multi_table/_properties/cardinality.py
- tests/integration/reports/multi_table/_properties/test_cardinality.py
- tests/integration/reports/multi_table/test_quality_report.py
- tests/unit/reports/multi_table/_properties/test_cardinality.py
> Multi table quality report should handle multi-foreign keys (to same parent)

- sdmetrics/reports/multi_table/_properties/__init__.py
- sdmetrics/reports/multi_table/_properties/base.py
- sdmetrics/reports/multi_table/_properties/cardinality.py
- sdmetrics/reports/multi_table/_properties/relationship_validity.py
- tests/integration/reports/multi_table/_properties/test_relationship_validity.py
- tests/unit/reports/multi_table/_properties/test_base.py
- tests/unit/reports/multi_table/_properties/test_cardinality.py
- tests/unit/reports/multi_table/_properties/test_relationship_validity.py
CU-86ayg9y9r
Resolve #469
The visualization is @npatki :
> Add `Relationship Validity` property

- sdmetrics/column_pairs/statistical/referential_integrity.py
- tests/unit/column_pairs/statistical/test_referential_integrity.py
> Fix ReferentialIntegrity NaN handling

- sdmetrics/reports/single_table/_properties/data_validity.py
- tests/integration/reports/multi_table/_properties/test_data_validity.py
- tests/integration/reports/multi_table/test_diagnostic_report.py
> KeyUniqueness metric should only be applied to primary and alternate keys

- pyproject.toml
> Adding support for copulas 0.10+

- .github/workflows/integration.yml
- .github/workflows/lint.yml
- .github/workflows/minimum.yml
- .github/workflows/readme.yml
- .github/workflows/unit.yml
- INSTALL.md
- pyproject.toml
- sdmetrics/__init__.py
- sdmetrics/reports/base_report.py
- sdmetrics/single_table/table_structure.py
- tasks.py
- tests/unit/column_pairs/statistical/test_correlation_similarity.py
- tests/unit/reports/test_base_report.py
- tests/unit/test___init__.py
- tests/unit/test_visualization.py
- tox.ini
> Add Python 3.12 support

- .github/workflows/static_code_analysis.yml
- pyproject.toml
- tests/test_tasks.py
CU-86azzkknb
Resolve #552
Resolve #555
> Add bandit workflow

- sdmetrics/timeseries/ml_scorers.py
- sdmetrics/utils.py
- tests/integration/timeseries/test_timeseries.py
- tests/unit/test_utils.py
> `LSTMDetection` metric crashes when there are multiple context columns

- .github/workflows/integration.yml
> Change integration workflow job name to integration

- pyproject.toml
> Restrict numpy to less than 2.0.0

- sdmetrics/reports/single_table/_properties/column_pair_trends.py
- tests/integration/reports/single_table/_properties/test_column_pair_trends.py
- tests/unit/reports/single_table/_properties/test_column_pair_trends.py
> ColumnPairTrends score depends on the data index

- tests/unit/column_pairs/statistical/test_referential_integrity.py
> Update Referential Integrity metric to support NaNs in child column 

- sdmetrics/timeseries/base.py
- sdmetrics/timeseries/detection.py
- tests/integration/timeseries/test_timeseries.py
- tests/unit/timeseries/__init__.py
- tests/unit/timeseries/test_timeseries.py
> Cast datetime columns to `datetime` in  LSTMDetection

- sdmetrics/visualization.py
- tests/unit/test_visualization.py
> LinAlgError when plotting data that is constant

- sdmetrics/visualization.py
- tests/unit/test_visualization.py
> X-axis for the bar plot should be labeled `Value` instead of `Category`

- pyproject.toml
- sdmetrics/base.py
- sdmetrics/reports/base_report.py
- sdmetrics/reports/single_table/plot_utils.py
- sdmetrics/reports/utils.py
- sdmetrics/single_table/privacy/base.py
- sdmetrics/single_table/privacy/util.py
- sdmetrics/visualization.py
- tests/unit/multi_table/statistical/test_cardinality_shape_similarity.py
- tests/unit/reports/multi_table/_properties/test_structure.py
- tests/unit/reports/single_table/_properties/test_column_shapes.py
- tests/unit/reports/single_table/_properties/test_structure.py
- tests/unit/reports/single_table/_properties/test_synthesis.py
- tests/unit/single_column/statistical/test_category_adherence.py
fix lint after ruff-0.7.1 release
> Fix lint + Pin ruff version

- .github/workflows/integration.yml
- .github/workflows/unit.yml
- .gitignore
- tasks.py
> Update codecov and add flag for integration tests

- .github/workflows/prepare_release.yml
- codecov.yml
- scripts/release_notes_generator.py
This PR:
1. Uses the correct library to create release notes
2. Updates the command that runs bandit
> Fix release prep workflow

- HISTORY.md
- static_code_analysis.txt
> v0.17.1 Release Preparation

- HISTORY.md
- static_code_analysis.txt
> v0.18.0 Release Preparation

- HISTORY.md
- static_code_analysis.txt
> v0.20.0 Release Preparation

- .github/workflows/prepare_release.yml
- scripts/check_for_prereleases.py
- tests/test_scripts.py
> Check pyproject for prerelease dependencies

- Makefile
- RELEASE.md
> Update release documentation

- pyproject.toml
- sdmetrics/__init__.py
This is an auto-generated PR that bumps the version to the next candidate.
> Automated Bump Version Candidate
